version: '3.3'
services:
  php:
    container_name: php-supadupa
    build: ./php
    volumes:
      - ./www:/var/www
    tty: true
  composer_installation:
    container_name: composer-installation
    image: composer
    working_dir: /var/www
    volumes:
      - ./www:/var/www
    command: composer install --ignore-platform-reqs
